# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import KeyTransfer_pb2 as KeyTransfer__pb2


class KeyTransferStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OnKeyFromCQP = channel.unary_unary(
                '/cqp.remote.KeyTransfer/OnKeyFromCQP',
                request_serializer=KeyTransfer__pb2.Key.SerializeToString,
                response_deserializer=KeyTransfer__pb2.Empty.FromString,
                )
        self.OnKeyFromSatellite = channel.unary_unary(
                '/cqp.remote.KeyTransfer/OnKeyFromSatellite',
                request_serializer=KeyTransfer__pb2.Key.SerializeToString,
                response_deserializer=KeyTransfer__pb2.Empty.FromString,
                )


class KeyTransferServicer(object):
    """Missing associated documentation comment in .proto file."""

    def OnKeyFromCQP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnKeyFromSatellite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KeyTransferServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OnKeyFromCQP': grpc.unary_unary_rpc_method_handler(
                    servicer.OnKeyFromCQP,
                    request_deserializer=KeyTransfer__pb2.Key.FromString,
                    response_serializer=KeyTransfer__pb2.Empty.SerializeToString,
            ),
            'OnKeyFromSatellite': grpc.unary_unary_rpc_method_handler(
                    servicer.OnKeyFromSatellite,
                    request_deserializer=KeyTransfer__pb2.Key.FromString,
                    response_serializer=KeyTransfer__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cqp.remote.KeyTransfer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KeyTransfer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def OnKeyFromCQP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cqp.remote.KeyTransfer/OnKeyFromCQP',
            KeyTransfer__pb2.Key.SerializeToString,
            KeyTransfer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OnKeyFromSatellite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cqp.remote.KeyTransfer/OnKeyFromSatellite',
            KeyTransfer__pb2.Key.SerializeToString,
            KeyTransfer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
