# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KeyTransfer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

from google.protobuf.empty_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11KeyTransfer.proto\x12\ncqp.remote\x1a\x1bgoogle/protobuf/empty.proto\"2\n\x03Key\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\r\n\x05seqID\x18\x02 \x01(\x04\x12\x0f\n\x07localID\x18\x03 \x01(\t\"\x07\n\x05\x45mpty2{\n\x0bKeyTransfer\x12\x32\n\x0cOnKeyFromCQP\x12\x0f.cqp.remote.Key\x1a\x11.cqp.remote.Empty\x12\x38\n\x12OnKeyFromSatellite\x12\x0f.cqp.remote.Key\x1a\x11.cqp.remote.EmptyP\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'KeyTransfer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _KEY._serialized_start=62
  _KEY._serialized_end=112
  _EMPTY._serialized_start=114
  _EMPTY._serialized_end=121
  _KEYTRANSFER._serialized_start=123
  _KEYTRANSFER._serialized_end=246
# @@protoc_insertion_point(module_scope)
